redis:
  image: redis
  ports:
    - "6379:6379"
web0:
  build: .
  command: bundle exec puma -b tcp://0.0.0.0:5000
  volumes:
    - .:/usr/src/app
  ports:
    - "5000"
  links:
    - redis
  environment:
    REDIS_URL: redis://redis:6379
    SESSION_SECRET: supersavesecret
    NAME: WEB0
web1:
  build: .
  command: bundle exec puma -b tcp://0.0.0.0:5000
  volumes:
    - .:/usr/src/app
  ports:
    - "5000"
  links:
    - redis
  environment:
    REDIS_URL: redis://redis:6379
    SESSION_SECRET: supersavesecret
    NAME: WEB1
web2:
  build: .
  command: bundle exec puma -b tcp://0.0.0.0:5000
  volumes:
    - .:/usr/src/app
  ports:
    - "5000"
  links:
    - redis
  environment:
    REDIS_URL: redis://redis:6379
    SESSION_SECRET: supersavesecret
    NAME: WEB2
haproxy:
  build: ./haproxy
  ports:
    - "8081:8081"
  links:
    - web0
    - web1
    - web2
